### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [datkt/sodium#1]
Hi @jwerle, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by jwerle** [comment]
Hi @samuel-lucas6,

Thanks for reaching out. I have not been able to come back to this project. The bindings here are for Kotlin/Native and targets users who intend to do systems programming. I would not recommend this library anymore for general Kotlin programming. You may remove it from the list.

**Comment by samuel-lucas6** [comment]
Thanks for getting back to me.

**Comment by jwerle** [comment]
@samuel-lucas6 No problem! Best of luck with the house keeping on https://github.com/jedisct1/libsodium-doc/pull/156
